config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :admins , controllers: { sessions: 'admins/sessions' , registrations: 'admins/registrations'}
  devise_for :librarians, controllers: { sessions: 'librarians/sessions' , registrations: 'librarians/registrations'}
  devise_for :students, controllers: { sessions: 'students/sessions' , registrations: 'students/registrations'}
  resources :books
  resources :librarians
  resources :admins
 
  get 'home/index'
  resources :students
  resources :covers
  resources :transactions

  root "home#index"
  get '/search' => 'books#search', :as => 'search'
  get '/returnBook' => 'books#returnBook', :as => 'returnBook'
  get '/checkout' => 'books#checkout', :as => 'checkout'
  get '/books_students' => 'books#books_students', :as => 'books_students'
  get '/list_checkedoutBooksAndStudentsAdmin' => 'books#list_checkedoutBooksAndStudentsAdmin', :as => 'list_checkedoutBooksAndStudentsAdmin'
  get '/list_checkedoutBooks' => 'books#list_checkedoutBooks', :as => 'list_checkedoutBooks'
  get '/show_librarians' => 'admins#show_librarians', :as => 'show_librarians'
  get '/restricted' => 'librarians#restricted', :as => 'restricted'
  get '/show_students' => 'admins#show_students', :as => 'show_students'
  get '/show_books' => 'admins#show_books', :as => 'show_books'
  get '/add_books' => 'books#new', :as => 'add_books'
  get '/add_students' => 'students#new', :as => 'add_students'
  get '/add_librarians' => 'librarians#new', :as => 'add_librarians'
  get '/getBookmarkBooks' => 'books#getBookmarkBooks', :as => 'getBookmarkBooks'
  get '/librarian_book_view' => 'books#librarian_book_view', :as => 'librarian_book_view'
  get '/getStudentBookFine' => 'books#getStudentBookFine', :as => 'getStudentBookFine'
  get '/viewBookHistory' => 'books#viewBookHistory', :as => 'viewBookHistory'
  get '/getOverdueBooks' => 'books#getOverdueBooks', :as => 'getOverdueBooks'
  get 'transactions/index'
  get 'transactions/show'
  get 'transactions/edit'
  get 'transactions/update'
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admins/_form.html.erb
<div class="table table-bordered table-striped col-md-6 container  py-5 h-100">
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="mb-3">
    <%= form.label :Nom, { class: "form-label"} %><br />
    <%= form.text_field :name %>
  </div>

  <div class="mb-3">
    <%= form.label :email, { class: "form-label"} %><br />
    <%= form.text_field :email %>
  </div>

  <div class="mb-3">
    <%= form.label :password, { class: "form-label"} %><br />
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit "Enregistrer", class:"p-2 mb-2 bg-primary text-white" %>
  </div>
</div>
<% end %>

app/views/admins/add_books.html.erb
<div class="table table-bordered table-striped px-md-2 container  py-5 h-100">
<%= render 'form', book: @book %>

app/views/admins/add_librarians.html.erb
<%= render 'form', librarian: @librarian %>

app/views/admins/add_students.html.erb
<%= render 'form', student: @student %>

app/views/admins/edit.html.erb
<div class="table table-bordered table-striped px-md-6 container  py-5 h-100">
<h1>Editer Admin</h1>

<%= render 'form', admin: @admin %>

<!--<%= link_to 'Afficher', @admin %> |-->
<%= link_to 'Retour', admins_path, class:"p-2 mb-2 bg-success text-white" %>

app/views/admins/index.html.erb
<div class="table table-bordered table-striped px-md-2 container  py-5 h-100">
<p id="notice"><%= notice %></p>

<h1>Panneau d'Administration</h1>

Nom: <%= current_admin.name %><br>
Email: <%= current_admin.email %><br> 

app/views/admins/new.html.erb
<div class="table table-bordered table-striped px-md-2 container  py-5 h-100">
<h1>Nouvel Administrateur</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<div class="table table-bordered table-striped px-md-2 container  py-5 h-100">
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Retour', book_admins_path %>

app/views/admins/show_books.html.erb
<div class="table table-bordered table-striped px-md-2 container  py-5 h-100">
<h1>Livres</h1>

<%= form_tag(search_path, :method => "get" , :required => true) do %>  
  
  <%= radio_button_tag(:search_by,"title",:checked => true,) %>Titre
  <%= radio_button_tag(:search_by, "authors")%>Auteurs
  <%= radio_button_tag(:search_by, "published")%>Date Publication
  
    <%= search_field_tag :search, params[:search], placeholder: "Chercher" , :required => true %>  
      <%= button_tag do%> 
	  <%= t('Search')%>
	  <% end %>

<% end %>
<table>
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Titre</th>
      <th>Auteurs</th>
      <th>Langue</th>
      <th>Quantité Disponible</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= book.authors %></td>
        <td><%= book.language %></td>
        <td><%= book.available_quantity %></td>
        <% if current_admin.nil? %>          
          <td><%= link_to 'Checkout', controller: "books", action: "checkout", id: book, class:"p-3 mb-2 bg-primary text-white" %></td> 
        <% else %>
		  <td><%= link_to 'Afficher', book, class:"p-3 mb-2 bg-primary text-white" %></td>
		  <td><%= link_to 'Editer', edit_book_path(book), class:"p-3 mb-2 bg-success text-white" %></td>
		  <!--<td><%= link_to 'Supprimer', book, method: :delete, data: { confirm: 'Are you sure?' },class:"p-3 mb-2 bg-danger text-white" %></td>-->
      <td><%= link_to 'Historique', controller: "books", action: "viewBookHistory", id: book , class: 'custom-link' %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/show_librarians.html.erb
<div class="table table-bordered table-striped px-md-2 container  py-5 h-100">
<h1>Liste Bibliothecaires</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Email</th>
      <th>Approuvé</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @librarians.each do |librarian| %>
      <tr>
        <td><%= librarian.name %></td>
        <td><%= librarian.email %></td>
        <td><%= librarian.approved %></td>
        <td><%= link_to 'Afficher', librarian, class:"p-3 mb-2 bg-primary text-white" %></td>
        <td><%= link_to 'Editer/Approuver', edit_librarian_path(librarian), class:"p-3 mb-2 bg-success text-white" %></td>
        <td><%= link_to 'Supprimer', librarian, method: :delete, data: { confirm: 'Vouler-vous vraiment supprimer?' }, class:"p-3 mb-2 bg-danger text-white" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/admins/show_students.html.erb
<div class="table table-bordered table-striped px-md-2 container  py-5 h-100">
<h1>Liste des Etudiants</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
		    <td><%= link_to 'Afficher', student, class:"p-3 mb-2 bg-primary text-white" %></td>
        <td><%= link_to 'Editer', edit_student_path(student), class:"p-3 mb-2 bg-success text-white" %></td>
        <td><%= link_to 'Supprimer', student, method: :delete, data: { confirm: 'Vouler-vous vraiment supprimer?' }, class:"p-3 mb-2 bg-danger text-white" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>