config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :admins , controllers: { sessions: 'admins/sessions' , registrations: 'admins/registrations'}
  devise_for :librarians, controllers: { sessions: 'librarians/sessions' , registrations: 'librarians/registrations'}
  devise_for :students, controllers: { sessions: 'students/sessions' , registrations: 'students/registrations'}
  resources :books
  resources :librarians
  resources :admins
 
  get 'home/index'
  resources :students
  resources :covers
  resources :transactions

  root "home#index"
  get '/search' => 'books#search', :as => 'search'
  get '/returnBook' => 'books#returnBook', :as => 'returnBook'
  get '/checkout' => 'books#checkout', :as => 'checkout'
  get '/books_students' => 'books#books_students', :as => 'books_students'
  get '/list_checkedoutBooksAndStudentsAdmin' => 'books#list_checkedoutBooksAndStudentsAdmin', :as => 'list_checkedoutBooksAndStudentsAdmin'
  get '/list_checkedoutBooks' => 'books#list_checkedoutBooks', :as => 'list_checkedoutBooks'
  get '/show_librarians' => 'admins#show_librarians', :as => 'show_librarians'
  get '/restricted' => 'librarians#restricted', :as => 'restricted'
  get '/show_students' => 'admins#show_students', :as => 'show_students'
  get '/show_books' => 'admins#show_books', :as => 'show_books'
  get '/add_books' => 'books#new', :as => 'add_books'
  get '/add_students' => 'students#new', :as => 'add_students'
  get '/add_librarians' => 'librarians#new', :as => 'add_librarians'
  get '/getBookmarkBooks' => 'books#getBookmarkBooks', :as => 'getBookmarkBooks'
  get '/librarian_book_view' => 'books#librarian_book_view', :as => 'librarian_book_view'
  get '/getStudentBookFine' => 'books#getStudentBookFine', :as => 'getStudentBookFine'
  get '/viewBookHistory' => 'books#viewBookHistory', :as => 'viewBookHistory'
  get '/getOverdueBooks' => 'books#getOverdueBooks', :as => 'getOverdueBooks'
  get 'transactions/index'
  get 'transactions/show'
  get 'transactions/edit'
  get 'transactions/update'
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      if !current_student.nil?
          sign_out :student
      end
      if !current_admin.nil?
          sign_out :admin
      end
    #    if !current_admin_guest.nil?
    #       sign_out :admin_guest
    #    end
      if !current_librarian.nil?
          sign_out :librarian
      end

      # if !current_student_guest.nil?
      #     sign_out :student_guest
      # end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="table table-bordered table-striped px-md-2 container  py-5 h-100">
<h1 class="text-center">BIENVENUS SUR BIBLIO-CFPT</h1>
<p id="notice"><%= notice %></p>
<div class="container">
<table class="table table-bordered table-striped text-center">
	<th><strong>Votre Bibliothèque en Ligne</strong></th>
	<th width='50%'><strong >Mode d'emploi</strong></th>
    <tr><td><strong>Vous êtes Etudiant</strong></td>
    <td rowspan="6" class="position">Vous pouvez acceder à l'application en fonction de votre profil : Administrateur, Bibliothécaire ou Étudiant. Un lien d’inscription et de connexion est disponible.<br>
    Un étudiant s'enregistre et se connecte sur la plateforme et peut faire des emprunts de livres. Il peut emprunter autant de livres pour une durée de 15 jours.<br>
    Pour etre bibliothecaire Vous devez vous inscrire en utilisant le lien d'inscription du bibliothécaire, puis etre approuver par l'administrateur.<br>
    Un administrateur est capable d'effectuer toutes les opérations effectuées par le bibliothécaire ou l'étudiant. L'administrateur est capable de :Créer/Modifier des comptes Bibliothécaire ou Étudiant
    Créer/Modifier/Supprimer des bibliothèques et des livres.
    Afficher la liste des utilisateurs (étudiants et bibliothécaires) et les détails de leur profil (sauf mot de passe)
    Consultez la liste des livres, ainsi que des informations détaillées.
    Consultez la liste des livres prétés.
    Consultez la liste des étudiants dont les livres sont en retard.
    Consultez l’historique d’emprunt de chaque livre.
    Supprimer un étudiant/un livre/un bibliothécaire du système
    
    </td></tr>

    <tr><td><%= link_to 'Connexion Etudiant', new_student_session_path, class:"p-3 mb-2 bg-success text-white" %>
    <%= link_to 'Connexion Invité', students_path, method: :post, class:"p-3 mb-2 bg-success text-white" %>
    </td></tr>
	<tr><td><strong>Vous êtes Bibliothècaire</strong></td></tr>
    <tr><td><%= link_to 'Connexion Bibliothècaire', new_librarian_session_path, class:"p-3 mb-2 bg-success text-white" %>
    <%= link_to 'Connexion Bibliothècaire', librarians_path,method: :post, class:"p-3 mb-2 bg-success text-white" %>
    </td></tr>
	
	<tr><td><strong>Vous êtes Administrateur</strong></td></tr>
    
    
    <tr><td><%= link_to 'Connexion Administrateur', new_admin_session_path, class:"p-3 mb-2 bg-success text-white" %>
   <%= link_to 'Connexion Admin Invité', admins_path, method: :post, class:"p-3 mb-2 bg-success text-white" %></td>
    </tr>
</table>
<div>