config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :admins , controllers: { sessions: 'admins/sessions' , registrations: 'admins/registrations'}
  devise_for :librarians, controllers: { sessions: 'librarians/sessions' , registrations: 'librarians/registrations'}
  devise_for :students, controllers: { sessions: 'students/sessions' , registrations: 'students/registrations'}
  resources :books
  resources :librarians
  resources :admins
 
  get 'home/index'
  resources :students
  resources :covers
  resources :transactions

  root "home#index"
  get '/search' => 'books#search', :as => 'search'
  get '/returnBook' => 'books#returnBook', :as => 'returnBook'
  get '/checkout' => 'books#checkout', :as => 'checkout'
  get '/books_students' => 'books#books_students', :as => 'books_students'
  get '/list_checkedoutBooksAndStudentsAdmin' => 'books#list_checkedoutBooksAndStudentsAdmin', :as => 'list_checkedoutBooksAndStudentsAdmin'
  get '/list_checkedoutBooks' => 'books#list_checkedoutBooks', :as => 'list_checkedoutBooks'
  get '/show_librarians' => 'admins#show_librarians', :as => 'show_librarians'
  get '/restricted' => 'librarians#restricted', :as => 'restricted'
  get '/show_students' => 'admins#show_students', :as => 'show_students'
  get '/show_books' => 'admins#show_books', :as => 'show_books'
  get '/add_books' => 'books#new', :as => 'add_books'
  get '/add_students' => 'students#new', :as => 'add_students'
  get '/add_librarians' => 'librarians#new', :as => 'add_librarians'
  get '/getBookmarkBooks' => 'books#getBookmarkBooks', :as => 'getBookmarkBooks'
  get '/librarian_book_view' => 'books#librarian_book_view', :as => 'librarian_book_view'
  get '/getStudentBookFine' => 'books#getStudentBookFine', :as => 'getStudentBookFine'
  get '/viewBookHistory' => 'books#viewBookHistory', :as => 'viewBookHistory'
  get '/getOverdueBooks' => 'books#getOverdueBooks', :as => 'getOverdueBooks'
  get 'transactions/index'
  get 'transactions/show'
  get 'transactions/edit'
  get 'transactions/update'
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BiblioCFPT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'style.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <%= link_to "Biblio CFPT", root_path, class: "navbar-brand bg-transparent" %>
    
      <div class="collapse navbar-collapse justify-content-end " id="navbarNavAltMarkup">
        <div class="navbar-nav" id="menu">
          <% if student_signed_in?%>
          <%= link_to "Logout", destroy_student_session_path, method: :delete, class:"text-bg-primary p-3" %>
          <%= link_to 'Retour', students_path, class:"text-bg-primary p-3" %>
          <%= link_to "Editer profil", edit_student_path(current_student), class:"text-bg-primary p-3" %>
          <%= link_to 'Tous les Livres', books_students_path, class:"text-bg-primary p-3" %>
          <%= link_to 'Votre activité (Emprunts)', getBookmarkBooks_path, class:"text-bg-primary p-3" %>
          
          
          <%end%>
          <% if librarian_signed_in?%>
          <%= link_to "Logout", destroy_librarian_session_path, method: :delete, class:"text-bg-primary p-3"%>
          <%= link_to 'Retour', librarians_path, class: "text-bg-primary p-3" %>
          <%= link_to 'Editer Profil', edit_librarian_path(current_librarian), class:"text-bg-primary p-3" %></td>
          <%= link_to 'Ajout Livre', new_book_path, class: "text-bg-primary p-3" %>
          <%= link_to 'Tous les Livres', librarian_book_view_path, class:"text-bg-primary p-3" %>
          <%= link_to 'Livres empruntés', list_checkedoutBooks_path, class:"text-bg-primary p-3" %>
          <%= link_to 'Historique des Livres empruntés ', list_checkedoutBooksAndStudentsAdmin_path, class:"text-bg-primary p-3" %>
          <%= link_to 'Delais dépassé ', getOverdueBooks_path, class:"text-bg-primary p-3" %>
          
          <%end%>
          <% if admin_signed_in? %>
          <%= link_to "Logout", destroy_admin_session_path, method: :delete, class:"text-bg-primary p-3"%>
          <%= link_to 'Back', admins_path, class:"text-bg-primary p-3" %>
          <%= link_to 'Editer Profil', edit_admin_path(current_admin), class:"text-bg-primary p-3" %>
          <%= link_to 'Ajout Biblothècaire', new_librarian_path, class:"text-bg-primary p-3" %>
          <%= link_to 'Voir Bibliothècaires', show_librarians_path, class:"text-bg-primary p-3" %>
          <%= link_to 'Ajout Etudiant', new_student_path, class:"text-bg-primary p-3" %>
          <%= link_to 'Liste Etudiants', show_students_path, class:"text-bg-primary p-3" %>
          <%= link_to 'Liste Etudiant/Delais dépassé', getOverdueBooks_path, class:"text-bg-primary p-3" %>
          
          <%= link_to 'Ajout Livre', add_books_path, class:"text-bg-primary p-3" %>
          <%= link_to 'Liste Livres', show_books_path, class:"text-bg-primary p-3" %>
          <%= link_to 'Livres empruntés', list_checkedoutBooks_path, class:"text-bg-primary p-3" %>

          <%end%>
             
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>